<?php

    if(isset($_GET['k'])) $k = $_GET['k']; else exit;
    if(isset($_GET['i'])) $i = $_GET['i']; else $i = 0;
    
    require_once 'cookie.php'; require_once '../Quantico'.$tmp.'.php'; use Quantico as Q;
    
    $ke = explode('@', $k); $ord = substr($ke[1],-2); if($ord != '.3' && $ord != '.4' && $ord != '.5' && $ord != '.6' && $ord != '.7' && $ord != '.8' && $ord != '.9' && $ord != '.p' && $ord != '.m' && $ord != '.q' && $ord != '.w' && $ord != '.x' && $ord != '.y' && $ord != '.z') $ord = false; else $ke[1] = substr($ke[1],0,-2); $v = str_replace('.2', '@0.0', $ke[1]);
    if(isset($ke[5]) && $ke[5]) { $single = $ke[5]; for($a=6, $u=count($ke); $a<$u; $a++) $single .= '@'.$ke[$a]; } else { $single = false; if($ke[4] == 0) { $ora = strtotime(gmdate("M d Y H:i:s", time())) + $Qgmt; $y[0] = date("d", $ora); $y[1] = date("m", $ora); $y[2] = date("Y", $ora); $z[0] = $y[0]; $z[1] = $y[1]; $z[2] = $y[2]; $inizio = 0; $fine = $Qposmax - 1; $dat = 0; } else { $x = explode(':', $ke[2]); $y = explode('-', $x[0]); $z = explode('-', $x[1]); $inizio = $ke[3]; $fine = $ke[4]; $dat = 1; } if($ke[2] == '0-0-0:0-0-0') { $ora = strtotime(gmdate("M d Y H:i:s", time())) + $Qgmt; $y[0] = date("d", $ora); $y[1] = date("m", $ora); $y[2] = date("Y", $ora); $z[0] = $y[0]; $z[1] = $y[1]; $z[2] = $y[2]; $dat = 0; }} $k = $ke[0].'@'.$ke[1]; $lng = file('language/'.rtrim($dbtype[4]).'/view.php',FILE_IGNORE_NEW_LINES);

?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?=rtrim($dbtype[4])?>">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="Content-Language" content="<?=rtrim($dbtype[4])?>">
    <meta name="author" content="Piazzi Raffaele">
    <title>QuanticoDB</title>
    <script type="text/javascript" src="js/jquery-2.1.4.min.js"></script>
    <script type="text/javascript" src="js/msgbox/msgbox.js"></script>
    <link type="text/css" rel="stylesheet" href="css/msgbox.css" />
    <link type="text/css" rel="stylesheet" href="css/style.css" />
    <link rel="shortcut icon" href="images/favicon.ico" />
    <script type='text/javascript'> sid = "<?=$i?>";
        function dettagli_json(msg,x,y,z,id,type) { var json = JSON.parse(msg); var b = 0; var c = 0; var c1 = 'cl1'; var c2 = 'cl3'; if(type) { c1 = 'cl4'; c2 = 'cl5'; } msg = '<table id="'+id+z+'" border="0" width="100%" cellspacing="0" cellpadding="0"><tr><td class="td1 '+c1+'">KEY</td><td class="td1 '+c2+'"><?=$lng[3]?></td><td class="td1">Data</td></tr></tr>';
            if(json.associated) { // --------> Associato o Modello
                for(var a=0; a<json.associated.length; a++) { var p = json.associated[a].time.split(' '); p = p[0]+'&nbsp;'+p[1]+'&nbsp;'; b++; c = z+'-'+b; msg += '<tr><td class="td3"><span id="k'+c+'">'+sjin(json.associated[a]['K'])+'</span></td>';
                    if(type) msg += '<td class="td3 cl6"><span id="kv'+c+'">'+json.associated[a].value; else msg += '<td class="td3"><a href="javascript:modifica(\'v'+c+'\',1)"><span id="kv'+c+'">'+json.associated[a].value+'</a>'; 
                    msg += '<span id="v'+c+'"></span></span></td><td class="td3"><font size="1" title=" <?=$lng[4]?> : '+json.associated[a].time+' ">'+p+'</font></td></tr>';
                }
            }
            if(json.multiple) { // ----------> LINKATO
                for(var a=0; a<json.multiple.length; a++) { b++; c = 1; var lnk = ''; var key = json.multiple[a]; for(var d=0; d<key['N']; d++) { var v = key.value[d]; var t = key.time[d]; lnk += '<a href="javascript:espandi(\'s'+z+'-'+b+'-'+c+'\',\''+v+'\')"><span id="s'+z+'-'+b+'-'+c+'" title=" <?=$lng[5]?> : '+t+'">'+v+'</span></a> &nbsp; '; c++; }
                    if(key['N'] == key['T']) lnk += '<span class="ft1 cl9"><b>[</b>'+key['N']+'/'+key['T']+'<b>]</b></span><div id="sk'+z+'-'+b+'-0"></div>'; else { var p = z.split('-'); if(p[1]) { var k1 = '#k'+p[0]; for(var n=1; n<(p.length-1); n++) k1 += '-'+p[n]; k1 = $(k1).text().split(' ').join(''); } else var k1 = "<?=$ke[0]?>"; 
                    if(k1 == key['K']) { p = "<?=$ke[1]?>".split('.'); k1 = p[0]; } k1 += '#'+key['K']+'('+key['N']+':'+(key['N']+json['posmax'])+')'; k1 = window.btoa(k1); var k2 = window.btoa(y); lnk += '<span id="s'+z+'-'+b+'-'+c+'-'+key['N']+'"><a class="ft1 cl8" href="javascript:next(\''+k1+'\',\''+k2+'\',\'s'+z+'-'+b+'-'+c+'-'+key['N']+'\',8)"><b>[</b>'+key['N']+'/'+key['T']+'<b>]</b></a></span><div id="sk'+z+'-'+b+'-0"></div>'; }
                    msg += '<tr><td class="td3 cl7"><span class="ft0 bg2" id="k'+z+'-'+b+'">'+sjin(key['K'])+'</span></td><td class="td3">'+lnk+'</td><td class="td3"></td></tr>'; 
                }
            }
            if(json.cloned) { // ------------> CLONATO
                for(var a=0; a<json.cloned.length; a++) { b++; c = 1; var lnk = ''; var key = json.cloned[a]; for(var d=0; d<key['N']; d++) { var v = key.value[d]; var t = key.time[d]; lnk += '<a href="javascript:guarda(\'s'+z+'-'+b+'-'+c+'\',\''+v+'@'+key['K']+'\')"><span id="s'+z+'-'+b+'-'+c+'" title=" <?=$lng[6]?> : '+t+'">'+v+'</span></a> &nbsp;'; c++; };
                    if(key['N'] == key['T']) lnk += '<span class="ft1 cl9"><b>[</b>'+key['N']+'/'+key['T']+'<b>]</b></span><div id="sk'+z+'-'+b+'-0"></div>'; else { var p = z.split('-'); if(p[1]) { var k1 = '#k'+p[0]; for(var n=1; n<(p.length-1); n++) k1 += '-'+p[n]; k1 = $(k1).text().split(' ').join(''); } else var k1 = "<?=$ke[0]?>";
                    if(k1 == key['K']) { p = "<?=$ke[1]?>".split('.'); k1 = p[0]; } k1 += '@'+key['K']+'('+key['N']+':'+(key['N']+json['posmax'])+')'; k1 = window.btoa(k1); var k2 = window.btoa(y); lnk += '<span id="s'+z+'-'+b+'-'+c+'-'+key['N']+'"><a class="ft1 cl8" href="javascript:next(\''+k1+'\',\''+k2+'\',\'s'+z+'-'+b+'-'+c+'-'+key['N']+'\',9)"><b>[</b>'+key['N']+'/'+key['T']+'<b>]</b></a></span><div id="sk'+z+'-'+b+'-0"></div>'; }
                    msg += '<tr><td class="td3 cl7"><span class="ft0 bg7" id="k'+z+'-'+b+'">'+sjin(key['K'])+'</span></td><td class="td3">'+lnk+'</td><td class="td3"></td></tr>';
                } 
            } if(id == 't') var s = 'height:24px'; else var s = 'border-bottom:1px solid #CCD; height=0px'; msg += '<tr><td colspan="3" style="'+s+'"></td></tr></table>'; $('#' + x).append(msg);
        }
        function dettagli(x,y) { z = x.substring(1); w = "'" + x + "'";
            if($("#e" + z).length) { $("#m" + z).html(''); $("#a" + z).remove(); } else { $('#m' + z).html('&nbsp;&nbsp;<a href="javascript:modifica(' + w + ',3)"><img id="e' + z + '" src="images/s_on.bmp" border="0" width="7" height="8" title="<?=$lng[7]?>"></a> <a href="javascript:modifica(' + w + ',4)"><img src="images/x_off.bmp" border="0" title="<?=$lng[8]?>"></a> <a href="javascript:modifica(' + w + ',5)"><img src="images/ru_on.bmp" border="0" title="<?=$lng[9]?>"></a>'); }    
            if($("#t" + z).length) { $("#t" + z).remove(); $("#a" + z).remove(); } else { $.post('keyview.php', { type: 1, key: <?="'$k'"?>, val: y }, function(msg){ if(msg != 0) dettagli_json(msg,x,y,z,'t',false); });}
        }
        function valori(x,y) { z = x.substring(1);
            if($("#n" + z).length) { $("#n" + z).remove(); $("#a" + z).remove(); } else { $.post('keyview.php', { type: 1, key: <?="'$v'"?>, val: y, pos: z }, function(msg){ if(msg != 0) dettagli_json(msg,x,y,z,'n',false); });}
        }
        function modelli(x,y) { z = x.substring(1); w = $("#sk" + z).text();
            if(w.length) { $("#sk" + z).html(''); $('#' + x).css('color','#09C'); } else { $.post('keyview.php', { type: 6, key: <?="'$ke[0]'"?>, val: y, pos: z }, function(msg){ if(msg != 0) { $('#' + x).css('color','red'); x = 'sk'+z; dettagli_json(msg,x,y,z,'sk',true); }}); }
        }
        function modifica(x,y) {
            if(y == 0) { $.msgBox({ title: "QuanticoDB", content: "<?=$lng[10]?>", buttons: [{ value: "<?=$lng[11]?>" }, { value: "<?=$lng[12]?>" }],
                success: function (result) { if(result == "<?=$lng[11]?>") { z = x.substring(1); u = z.split('-'); k = sjout('k',z); kv = sjout('k',u[0]); kc = <?="'$ke[0] '"?>; ks = ''; s = 'k'; if(u.length > 3) { for(a=0; a<(u.length-2); a++) { s = s + u[a] + '-'; }; s = s.substring(0,s.length-1); ks = $("#" + s).text(); ks = $.trim(ks); s = 's'; for(a=0; a<(u.length-1); a++) { s = s + u[a] + '-'; }; s = s.substring(0,s.length-1); s = $("#" + s).text(); }; if(ks == '') { kc = kc + k; } else { kc = ks + ' ' + k; kv = s; }; $.post('keyview.php', { type: 3, key: kc, val: 0, pos: kv }, function(msg){ if(msg == 'OK') { $("#t" + u[0]).remove(); $("#m" + z).html(''); dettagli('v' + u[0],kv); } else error(); });}}});}
            else if(y == 1) { z = x.substring(1); w = "'" + x + "'"; if($("#qsx").length) { $("#" + x).html(''); } else { $("#" + x).append(' <input class="ykc" id="d' + z + '" type="text"> <a href="javascript:modifica(' + w + ',2)"><img id="qsx" src="images/s_on.bmp" border="0" width="7" height="8" title="<?=$lng[7]?>"></a> <a href="javascript:modifica(' + w + ',0)"><img src="images/x_off.bmp" border="0" title="<?=$lng[8]?>"></a>'); }}
            else if(y == 2) { z = x.substring(1); u = z.split('-'); k = sjout('k',z); kv = sjout('k',u[0]); kc = <?="'$ke[0] '"?>; kd = $("#d" + z).val(); ks = ''; s = 'k'; if(u.length > 3) { for(a=0; a<(u.length-2); a++) { s = s + u[a] + '-'; }; s = s.substring(0,s.length-1); ks = $("#" + s).text(); ks = $.trim(ks); s = 's'; for(a=0; a<(u.length-1); a++) { s = s + u[a] + '-'; }; s = s.substring(0,s.length-1); s = $("#" + s).text(); }; if(ks == '') { kc = kc + k; } else { kc = ks + ' ' + k; kv = s; }; if(kd != '') { $.post('keyview.php', { type: 2, key: kc, val: kd, pos: kv }, function(msg){ if(msg == 'OK') { $("#v" + z).html(''); $("#kv" + z).html(kd); } else error(); });} else { $("#v" + z).html(''); }}
            else if(y == 3) { z = x.substring(1); if($("#d" + z).length) { kd = $("#d" + z).val(); if(kd != '') { kv = sjout('k',z); kc = <?="'$ke[0]'"?>; $.post('keyview.php', { type: 2, key: kc, val: kv, pos: kd }, function(msg){ if(msg == 'OK') { $("#m" + z).html(''); $("#k" + z).html(kd); } else error(); }); }} else { $('#m' + z).html('').html(' <input class="ykc" id="d' + z + '" type="text"> <a href="javascript:modifica(' + w + ',3)"><img id="e' + z + '" src="images/s_on.bmp" border="0" width="7" height="8" title="<?=$lng[7]?>"></a> <a href="javascript:modifica(' + w + ',4)"><img src="images/x_off.bmp" border="0" title="<?=$lng[8]?>"></a> <a href="javascript:modifica(' + w + ',5)"><img src="images/ru_on.bmp" border="0" title="<?=$lng[9]?>"></a>'); }}  
            else if(y == 4) { $.msgBox({ title: "QuanticoDB", content: "<?=$lng[13]?>", buttons: [{ value: "<?=$lng[11]?>" }, { value: "<?=$lng[12]?>" }], 
                success: function (result) { if(result == "<?=$lng[11]?>") { z = x.substring(1); kv = sjout('k',z); kc = <?="'$ke[0]'"?>; $.post('keyview.php', { type: 3, key: kc, val: 0, pos: kv }, function(msg){ if(msg == 'OK') { $("#m" + z).html(''); $("#v" + z).html(''); dettagli('v' + z,kv); } else error(); });}}});}
            else if(y == 5) { z = x.substring(1); kv = sjout('k',z); kc = <?="'$ke[0]'"?>; if($("#a" + z).length == 0) { $.post('keyview.php', { type: 4, key: kc, val: kv, pos: z, sid: sid }, function(msg){ var json = JSON.parse(msg); msg = '<table id="a'+z+'" cellspacing="0" cellpadding="0" border="0" width="50%" align="center"><tr><td class="td1 cl1"><?=$lng[14]?></td><td class="td1 cl3"><?=$lng[15]?></td><td class="td1"><a href="javascript:chiudi('+z+',2)"><img id="x'+z+'" border="0" hspace="10" src="images/x_off.bmp" onmouseover="javascript:chiudi('+z+',1)" onmouseout="javascript:chiudi('+z+',0)" title="<?=$lng[16]?>"></a></td></tr>'; for(var a=0; a<json.length; a++) { var b = z+'-'+(a+1); msg += '<tr id="ar'+b+'"><td class="td3"><span id="ak'+b+'">'+json[a]+'</span></td><td class="td3"><input class="ykc" id="av'+b+'" type="text"></td><td class="td3"><a href="javascript:aggiungi(\''+b+'\',2)"><img id="ag'+b+'" border="0" hspace="10" src="images/ru_off.bmp" onmouseover="javascript:aggiungi(\''+b+'\',1)" onmouseout="javascript:aggiungi(\''+b+'\',0)" title="<?=$lng[17]?>"></a></td></tr>'; } msg += '<tr><td height="12" colspan="3"></td></tr></table>'; $('#' + x).append(msg); });}}
        }
        function cancellato(x,y) { z = x.substring(1);
            if($("#t" + z).length) { $("#t" + z).remove(); $("#a" + z).remove(); } else { $.post('keyview.php', { type: 7, key: <?="'$k'"?>, val: y, pos: z }, function(msg){ if(msg != 0) { $('#' + x).append(msg); }}); }
        }
        function cancellass(x,y) { $.msgBox({ title: "QuanticoDB", content: "<?=$lng[18]?>", buttons: [{ value: "<?=$lng[11]?>" }, { value: "<?=$lng[12]?>" }],
            success: function (result) { if(result == "<?=$lng[11]?>") { g = x.split('-'); v = g[0]; for(a=1; a<(g.length - 1); a++) v += '-' + g[a]; var z = sjout('k',v); var k = <?="'$ke[0]'"?>; k += '#' + z; z = sjout('k',g[0]); $.post('keyview.php', { type: 3, key: k, val: z, pos: y }, function(msg){ if(msg == 'OK') { $("#n" + x).remove(); $("#x" + x).remove(); $("#s" + x).remove(); } else error(); });}}});
        }
        function ordina(x,y,i,f,t) { if(t) { dag = $("#da_giorno").val(); dam = $("#da_mese").val(); daa = $("#da_anno").val(); ag = $("#a_giorno").val(); am = $("#a_mese").val(); aa = $("#a_anno").val(); } else { dag = 0; dam = 0; daa = 0; ag = 0; am = 0; aa = 0; } opz = dag + '-' + dam + '-' + daa + ':' + ag + '-' + am + '-' + aa + '@' + i + '@' + f;
	    	if(y == 0) { $("#" + x).attr("src","images/" + x + "_off.bmp"); } 
            else if(y == 1) { $("#" + x).attr("src","images/" + x + "_on.bmp"); } 
            else if(y == 2) { if(x == 'pac') location.href = 'view.php?k=<?=$k?>.3@' + opz; else if(x == 'piu') location.href = 'view.php?k=<?=$k?>.4@' + opz; else if(x == 'meno') location.href = 'view.php?k=<?=$k?>.5@' + opz; }
            else if(y == 3) { if(x == 'piu') location.href = 'view.php?k=<?=$k?>.6@' + opz; else if(x == 'meno') location.href = 'view.php?k=<?=$k?>.7@' + opz; else if(x == 'piuq') location.href = 'view.php?k=<?=$k?>.8@' + opz; else if(x == 'menoq') location.href = 'view.php?k=<?=$k?>.9@' + opz; }
            else if(y == 4) { if(x == 'pac') location.href = 'view.php?k=<?=$k?>.q@' + opz; else if(x == 'piu') location.href = 'view.php?k=<?=$k?>.p@' + opz; else if(x == 'meno') location.href = 'view.php?k=<?=$k?>.m@' + opz; }
            else if(y == 5) { if(x == 'piu') location.href = 'view.php?k=<?=$k?>.w@' + opz; else if(x == 'meno') location.href = 'view.php?k=<?=$k?>.x@' + opz; else if(x == 'piuq') location.href = 'view.php?k=<?=$k?>.y@' + opz; else if(x == 'menoq') location.href = 'view.php?k=<?=$k?>.z@' + opz; }
        }
        function aggiungi(x,y) {
	    	if(y == 0) { $("#ag" + x).attr("src","images/ru_off.bmp"); } else if(y == 1) { $("#ag" + x).attr("src","images/ru_on.bmp"); } else if(y == 2) { u = x.split('-'); k = sjout('ak',x); kp = sjout('k',u[0]); kv = $("#av" + x).val(); kc = <?="'$ke[0] '"?>; kc = kc + k; $.post('keyview.php', { type: 2, key: kc, val: kv, pos: kp }, function(msg){ if(msg == 'OK') $("#ar" + x).remove(); else error(); }); }
        }
        function view(x,y,z) {
            if(z == 0) { $("#" + x).attr("src","images/occhio_off.bmp"); } else if(z == 1) { $("#" + x).attr("src","images/occhio_on.bmp"); } else if(z == 2) { location.href = 'details.php?k=' + y + '@<?=$ke[1]?>@0-0-0:0-0-0@0@0&i=' + sid; }
        }
        function data() { fine = <?=($Qposmax-1)?>;
            dag = $("#da_giorno").val(); dam = $("#da_mese").val(); daa = $("#da_anno").val(); ag = $("#a_giorno").val(); am = $("#a_mese").val(); aa = $("#a_anno").val();
	    	location.href = 'view.php?k=<?=$k?>@' + dag + '-' + dam + '-' + daa + ':' + ag + '-' + am + '-' + aa + '@0@' + fine;
        }
        function part(x,y) {
            dag = $("#da_giorno").val(); dam = $("#da_mese").val(); daa = $("#da_anno").val(); ag = $("#a_giorno").val(); am = $("#a_mese").val(); aa = $("#a_anno").val();
	    	location.href = 'view.php?k=<?=$k?>@' + dag + '-' + dam + '-' + daa + ':' + ag + '-' + am + '-' + aa + '@' + x + '@' + y;
        }
        function pos(x,y) {
            location.href = 'view.php?k=<?=$k?>@0-0-0:0-0-0@' + x + '@' + y;
        }
        function sjout(x,y) {
        	return $('#'+ x + y).html().split('&nbsp;.&nbsp;').join('.');
        }
        function sjin(x) {
        	return x.split('.').join('&nbsp;.&nbsp;');
        }
        function espandi(x,y) { z = x.substring(1); g = z.split('-'); v = ''; for(a=0; a<(g.length - 1); a++) { v = v + g[a] + '-'; }; p = v + '0'; v = v.substring(0, (v.length - 1)); r = sjout('k',v); r = $.trim(r);
            if($("#x" + z).length) { $("#x" + z).remove(); $("#n" + z).remove(); $('#' + x).css('color','#09C'); } else { var a = $('#' + x).text(); $('#' + x).append('<a id="x' + z + '" href=javascript:cancellass("' + z + '","' + a + '")><img border="0" hspace="5" src="images/x_off.bmp" title="<?=$lng[19]?>"></a>'); $.post('keyview.php', { type: 1, key: r, val: y, pos: z }, function(msg){ if(msg != 0) { $('#' + x).css('color','red'); x = 'sk'+p; dettagli_json(msg,x,y,z,'n',false); }});}
        }
        function guarda(x,y) { z = x.substring(1); g = z.split('-'); v = ''; for(a=0; a<(g.length - 1); a++) { v = v + g[a] + '-'; }; p = v + '0'; v = v.substring(0, (v.length - 1)); r = sjout('k',v); r = $.trim(r);
            if($("#n" + z).length) { $("#n" + z).remove(); $('#' + x).css('color','#09C'); } else { $.post('keyview.php', { type: 6, key: r, val: y, pos: z }, function(msg){ if(msg != 0) { $('#' + x).css('color','red'); x = 'sk'+p; dettagli_json(msg,x,y,z,'n',true); }});}
        }
        function chiudi(x,y) {
        	if(y == 0) { $("#x" + x).attr("src","images/x_off.bmp"); } if(y == 1) { $("#x" + x).attr("src","images/x_on.bmp"); } if(y == 2) { $("#a" + x).remove(); }
        }
        function setdata(a,b,c,d,e,f,dat) { if(dat == 0) $("#xp").css('font-weight', 'bold'); else $("#xd").css('font-weight', 'bold');
            $("#da_giorno").val(a); $("#da_mese").val(b); $("#da_anno").val(c); $("#a_giorno").val(d); $("#a_mese").val(e); $("#a_anno").val(f);
        }
        function next(x,y,z,w) {
            $.post('keyview.php', { type: w, key: x, val: y, pos: z }, function(msg){ if(msg != 0) $('#' + z).html(msg); });
        }
        function error() {
            $.msgBox({ type: 'error', title: 'QuanticoDB', content: '<?=$lng[20]?>' });
        }
    </script> 
</head>
<body>
<?php
    $giorno = '<option selected value="01">01</option><option value="02">02</option><option value="03">03</option><option value="04">04</option><option value="05">05</option><option value="06">06</option><option value="07">07</option><option value="08">08</option><option value="09">09</option><option value="10">10</option><option value="11">11</option><option value="12">12</option><option value="13">13</option><option value="14">14</option><option value="15">15</option><option value="16">16</option><option value="17">17</option><option value="18">18</option><option value="19">19</option><option value="20">20</option><option value="21">21</option><option value="22">22</option><option value="23">23</option><option value="24">24</option><option value="25">25</option><option value="26">26</option><option value="27">27</option><option value="28">28</option><option value="29">29</option><option value="30">30</option><option value="31">31</option></select> ';
    $mese = '<option selected value="01">'.$lng[21].'</option><option value="02">'.$lng[22].'</option><option value="03">'.$lng[23].'</option><option value="04">'.$lng[24].'</option><option value="05">'.$lng[25].'</option><option value="06">'.$lng[26].'</option><option value="07">'.$lng[27].'</option><option value="08">'.$lng[28].'</option><option value="09">'.$lng[29].'</option><option value="10">'.$lng[30].'</option><option value="11">'.$lng[31].'</option><option value="12">'.$lng[32].'</option></select> ';
    $anno = '<option value="2017">2017</option><option value="2018">2018</option><option value="2019">2019</option><option value="2020">2020</option><option value="2021">2021</option><option value="2022">2022</option><option value="2023">2023</option><option value="2024">2024</option><option value="2025">2025</option><option value="2026">2026</option><option value="2027">2027</option><option value="2028">2028</option><option value="2029">2029</option><option value="2030">2030</option><option value="2031">2031</option><option value="2032">2032</option><option value="2033">2033</option><option value="2034">2034</option><option value="2035">2035</option><option value="2036">2036</option><option value="2037">2037</option><option value="2038">2038</option><option value="2039">2039</option><option value="2040">2040</option></select> ';
    $array = '<div align="center"><table border="0" width="800" cellspacing="0" cellpadding="0"><tr><td class="td2 cl1" title="'.$lng[33].'">&nbsp;Array&nbsp;</td>';
    $ordpiu = '<img id="piu" src="images/piu_off.bmp" onmouseover=javascript:ordina("piu",1) onmouseout=javascript:ordina("piu",0) title="'.$lng[34].'"></a>';
    $ordmeno = '<img id="meno" src="images/meno_off.bmp" onmouseover=javascript:ordina("meno",1) onmouseout=javascript:ordina("meno",0) title="'.$lng[35].'"></a>';
    $meno = 'onmouseover=javascript:ordina("menoq",1) onmouseout=javascript:ordina("menoq",0) title="'.$lng[35].'"></a>';
    $piu ='onmouseover=javascript:ordina("piuq",1) onmouseout=javascript:ordina("piuq",0) title="'.$lng[34].'"></a>';
    if($ke[1] != '0.0') {
        if(strpos($ke[1],'.0')) { $k = explode('.', $ke[1]); $key = $k[0]; for($a=1, $u=count($k)-1; $a<$u; $a++) $key .= '.'.$k[$a]; $tmp = $key; if($ord == '.4') $key .= '+'; elseif($ord == '.5') $key .= '-'; if($ke[2] == '0-0-0:0-0-0') { $val = Q\DB::out("#$key($inizio:$fine) $ke[0]"); $t = 0; } else { $val = Q\DB::out("#$key"."[$ke[2]]($inizio:$fine) $ke[0]"); $t = 1; }
            echo $array.'<td class="td2 cl2">'.$ke[0].' <a href=javascript:ordina("piu",2,'.$inizio.','.$fine.','.$t.')>'.$ordpiu.'<a href=javascript:ordina("meno",2,'.$inizio.','.$fine.','.$t.')>'.$ordmeno.'</td><td class="td2 cl3">'.$tmp.'</td></tr><tr><td height="10" colspan="3"></td></tr>';
            for($a=0; $a<$val['N']; $a++) { $v = Q\DB::out("$ke[0]#$tmp(0)", $val[$a]); $msg = $v[0]; for($c=1; $c<$v['N']; $c++) $msg .= '&nbsp; '.$v[$c]; $msg .= '&nbsp;&nbsp; <b><font face="Arial" color="#000" size="1">[</b> '.$v['N'].'/'.$v['T'].' <b>]</font></b>'; if(strpos($val[$a],"'") !== false) $href = '<a href=javascript:dettagli("v'.$a.'","'.$val[$a].'")>'; else $href = '<a href=\'javascript:dettagli("v'.$a.'","'.$val[$a].'")\'>'; echo '<tr><td class="td4">'.($inizio+$a).'</td><td id="v'.$a.'" class="td4">'.$href.'<span id="k'.$a.'">'.$val[$a].'</span></a><span id="m'.$a.'"></span></td><td class="td4 cl3">'.$msg.'</td></tr>'; }
        } elseif(strpos($ke[1],'.1')) { $si = true; $k = explode('.', $ke[1]); $key = $k[0]; for($a=1, $u=count($k)-1; $a<$u; $a++) $key .= '.'.$k[$a]; $tmp = $key; if($ord == '.3' or $ord == '.6' or $ord == '.7' or $ord == '.8' or $ord == '.9') { $si = false; if($ord == '.3') $ord = "!@$key"; elseif($ord == '.6') $ord = "!@$key+"; elseif($ord == '.7') $ord = "!@$key-"; elseif($ord == '.8') $ord = "!@$key+!"; elseif($ord == '.9') $ord = "!@$key-!"; else $ord = "@$key"; if($ke[2] == '0-0-0:0-0-0') { $val = Q\DB::out($ord."($inizio:$fine) $ke[0]",-1); $t = 0; } else { $val = Q\DB::out($ord."[$ke[2]]($inizio:$fine) $ke[0]",-1); $t = 1; }
                echo $array.'<td class="td2 cl2">'.$tmp.' <a href=javascript:ordina("piu",3,'.$inizio.','.$fine.','.$t.')>'.$ordpiu.'<a href=javascript:ordina("meno",3,'.$inizio.','.$fine.','.$t.')>'.$ordmeno.'</td><td class="td2 cl3">'.$lng[36].' <a href=javascript:ordina("piuq",3,'.$inizio.','.$fine.','.$t.')><img id="piuq" src="images/piuq_off.bmp" '.$piu.'<a href=javascript:ordina("menoq",3,'.$inizio.','.$fine.','.$t.')><img id="menoq" src="images/menoq_off.bmp" '.$meno.'</td></tr><tr><td height="10" colspan="3"></td></tr>';
                for($a=0; $a<$val['N']; $a++) echo '<tr><td class="td4">'.$a.'</td><td id="v'.$a.'" class="td4 cl2"><a href=\'javascript:modelli("s'.$a.'","'.$val['@'.$tmp][$a].'@'.$tmp.'")\'><span id="s'.$a.'">'.$val['@'.$tmp][$a].'</span></a></font><div id="sk'.$a.'"></div></td><td class="td4 cl3">'.$val['N.@'.$tmp][$a].'</td></tr>';
            } elseif($ord == '.4') $key .= '+'; elseif($ord == '.5') $key .= '-'; if($si) { if($ke[2] == '0-0-0:0-0-0') { $val = Q\DB::out("@$key($inizio:$fine) $ke[0]",-1); $t = 0; } else { $val = Q\DB::out("@$key"."[$ke[2]]($inizio:$fine) $ke[0]",-1); $t = 1; } $ok[0] = "\n"; $ok[1] = "\n"; $no[0] = "\n"; $no[1] = "\n"; $z = -1;
                echo $array.'<td class="td2 cl2">'.$ke[0].' <a href=javascript:ordina("piu",2,'.$inizio.','.$fine.','.$t.')>'.$ordpiu.'<a href=javascript:ordina("meno",2,'.$inizio.','.$fine.','.$t.')>'.$ordmeno.'</td><td class="td2 cl3">'.$tmp.' <a href=javascript:ordina("pac",2,'.$inizio.','.$fine.','.$t.')><img id="pac" src="images/pac_off.bmp" onmouseover=javascript:ordina("pac",1) onmouseout=javascript:ordina("pac",0) title="'.$lng[37].' ---> '.$tmp.' : '.$lng[36].'"></a></td></tr><tr><td height="10" colspan="3"></td></tr>';
                for($a=0; $a<$val['N']; $a++) {
                    if($val['-.'.$a]) { $j = array_search($val[$a],$no); if($j < 2) { $no[] = $val[$a]; $z++; $title = $lng[37].' : '.date('d M y - H:i:s',$val["t.$a"]);
                        echo '<tr><td class="td4">'.$z.'</td><td id="v'.$a.'" class="td4"><a href=javascript:cancellato("v'.$a.'","'.$val['-.'.$a].'")><span id="k'.$a.'" title="'.$title.'">'.$val[$a].'</span></a><span id="m'.$a.'"></span></td><td class="td4 cl1">'.$lng[37].'</td></tr>'; }
                    } else { $j = array_search($val[$a],$ok); if($j < 2) { $ok[] = $val[$a]; $z++; $v = Q\DB::out("$ke[0]@$tmp(0)", $val[$a]); $msg = $v[0]; for($c=1; $c<$v['N']; $c++) $msg .= '&nbsp; '.$v[$c]; $msg .= '&nbsp;&nbsp; <b><font face="Arial" color="#000" size="1">[</b> '.$v["N"].'/'.$v["T"].' <b>]</font></b>'; if(strpos($val[$a],"'") !== false) $href = '<a href=javascript:dettagli("v'.$a.'","'.$val[$a].'")>'; else $href = '<a href=\'javascript:dettagli("v'.$a.'","'.$val[$a].'")\'>';
                        echo '<tr><td class="td4">'.$z.'</td><td id="v'.$a.'" class="td4">'.$href.'<span id="k'.$a.'">'.$val[$a].'</span></a><span id="m'.$a.'"></span></td><td class="td4 cl3">'.$msg.'</td></tr>'; }
                    }
                }
            }
        } elseif(strpos($ke[1],'.2')) { $ok = true; $k = explode('.', $ke[1]); $key = $k[0]; for($a=1, $u=count($k)-1; $a<$u; $a++) $key .= '.'.$k[$a]; $tmp = $key;
            if($ord == '.3' || $ord == '.6' || $ord == '.7' || $ord == '.8' || $ord == '.9') { $ok = false; if($ord == '.6') $ord = "!@$ke[0]+"; elseif($ord == '.7') $ord = "!@$ke[0]-"; elseif($ord == '.8') $ord = "!@$ke[0]+!"; elseif($ord == '.9') $ord = "!@$ke[0]-!"; else $ord = "!@$ke[0]"; if($ke[2] == '0-0-0:0-0-0') { $val = Q\DB::out($ord."($inizio:$fine) $key",-1); $t = 0; } else { $val = Q\DB::out($ord."[$ke[2]]($inizio:$fine) $key",-1); $t = 1; }
                echo $array.'<td class="td2 cl2">'.$ke[0].' <a href=javascript:ordina("piu",3,'.$inizio.','.$fine.','.$t.')>'.$ordpiu.'<a href=javascript:ordina("meno",3,'.$inizio.','.$fine.','.$t.')>'.$ordmeno.'</td><td class="td2 cl3">'.$lng[36].' <a href=javascript:ordina("piuq",3,'.$inizio.','.$fine.','.$t.')><img id="piuq" src="images/piuq_off.bmp" '.$piu.'<a href=javascript:ordina("menoq",3,'.$inizio.','.$fine.','.$t.')><img id="menoq" src="images/menoq_off.bmp" '.$meno.'</td></tr><tr><td height="10" colspan="3"></td></tr>';
                for($a=0; $a<$val['N']; $a++) { $tipo = $ke[0].' : '.Q\DB::ver($val['@'.$ke[0]][$a].'@'.$ke[0]); echo '<tr><td class="td4">'.($inizio+$a).'</td><td class="td4 cl2"><a href=\'javascript:modelli("s'.$a.'","'.$val['@'.$ke[0]][$a].'@'.$ke[0].'")\'><span id="s'.$a.'" title="'.$tipo.'"></span>'.$val['@'.$ke[0]][$a].'</a>&nbsp;&nbsp;&nbsp; <a href=\'javascript:view("o'.$a.'","'.$val['@'.$ke[0]][$a].' '.$ke[0].'",2)\'><img id="o'.$a.'" src="images/occhio_off.bmp" onmouseover=\'javascript:view("o'.$a.'","'.$val['@'.$ke[0]][$a].'@'.$ke[0].'",1)\' onmouseout=\'javascript:view("o'.$a.'","'.$val['@'.$ke[0]][$a].'@'.$ke[0].'",0)\' title="'.$lng[38].'"></a><div id="sk'.$a.'"></div></td><td class="td4 cl3">'.$val['N.@'.$ke[0]][$a].'</td></tr>'; }
            } elseif($ord == '.q' || $ord == '.w' || $ord == '.x' || $ord == '.y' || $ord == '.z') { $ok = false; if($ord == '.w') $ord = "!$key+"; elseif($ord == '.x') $ord = "!$key-"; elseif($ord == '.y') $ord = "!$key+!"; elseif($ord == '.z') $ord = "!$key-!"; else $ord = "!$key"; if($ke[2] == '0-0-0:0-0-0') { $val = Q\DB::out("@$ke[0]($inizio:$fine) $ord",-1); $t = 0; } else { $val = Q\DB::out("@$ke[0]"."[$ke[2]]($inizio:$fine) $ord",-1); $t = 1; }
                echo $array.'<td class="td2 cl2">'.$tmp.' <a href=javascript:ordina("piu",5,'.$inizio.','.$fine.','.$t.')>'.$ordpiu.'<a href=javascript:ordina("meno",5,'.$inizio.','.$fine.','.$t.')>'.$ordmeno.'</td><td class="td2 cl3">'.$lng[36].' <a href=javascript:ordina("piuq",5,'.$inizio.','.$fine.','.$t.')><img id="piuq" src="images/piuq_off.bmp" '.$piu.'<a href=javascript:ordina("menoq",5,'.$inizio.','.$fine.','.$t.')><img id="menoq" src="images/menoq_off.bmp" '.$meno.'</td></tr><tr><td height="10" colspan="3"></td></tr>';
                for($a=0; $a<$val['N']; $a++) { if(strpos($val[$tmp][$a],"'") !== false) $href = '<a href=javascript:valori("v'.$a.'","'.$val[$tmp][$a].'")>'; else $href = '<a href=\'javascript:valori("v'.$a.'","'.$val[$tmp][$a].'")\'>'; echo '<tr><td class="td4">'.($inizio+$a).'</td><td id="v'.$a.'" class="td4 cl2">'.$href.'<span id="k'.$a.'">'.$val[$tmp][$a].'</span></a></td><td class="td4 cl3">'.$val['N.'.$tmp][$a].'</td></tr>'; }
            } elseif($ord == '.p') $key .= '+'; elseif($ord == '.m') $key .= '-'; if($ok) { if($ke[2] == '0-0-0:0-0-0') { $val = Q\DB::out("@$ke[0]($inizio:$fine) $key",-1); $t = 0; } else { $val = Q\DB::out("@$ke[0]"."[$ke[2]]($inizio:$fine) $key",-1); $t = 1; }
                echo $array.'<td class="td2 cl2">'.$ke[0].' <a href=javascript:ordina("pac",2,'.$inizio.','.$fine.','.$t.')><img id="pac" src="images/pac_off.bmp" onmouseover=javascript:ordina("pac",1) onmouseout=javascript:ordina("pac",0) title="'.$lng[37].' ---> '.$ke[0].' : '.$lng[36].'"></a></td><td class="td2 cl3">'.$tmp.' <a href=javascript:ordina("pac",4,'.$inizio.','.$fine.','.$t.')><img id="pacq" src="images/pac_off.bmp" onmouseover=javascript:ordina("pacq",1) onmouseout=javascript:ordina("pacq",0) title="'.$lng[37].' ---> '.$tmp.' : '.$lng[36].'"></a><a href=javascript:ordina("piu",4,'.$inizio.','.$fine.','.$t.')><img id="piuq" src="images/piu_off.bmp" '.$piu.'<a href=javascript:ordina("meno",4,'.$inizio.','.$fine.','.$t.')><img id="menoq" src="images/meno_off.bmp" '.$meno.'</td></tr><tr><td height="10" colspan="3"></td></tr>';
                for($a=0; $a<$val['N']; $a++) { 
                    if($val["-.$a"]) { $tipo = $ke[0].' : '.Q\DB::ver($val["p.$a"].'@'.$ke[0]); $title = $lng[37].' : '.date('d M Y - H:i:s',$val["t.$a"]); if(strpos($val[$a],"'") !== false) $href = '<a class="cl1" href=javascript:cancellato("v'.$a.'","'.$val["-.$a"].'")>'; else $href = '<a class="cl1" href=\'javascript:cancellato("v'.$a.'","'.$val["-.$a"].'")\'>';
                        echo '<tr><td class="td4">'.$a.'</td><td class="td4"><a href=\'javascript:modelli("s'.$a.'","'.$val["p.$a"].'@'.$ke[0].'")\'><span id="s'.$a.'" title="'.$tipo.'"></span>'.$val["p.$a"].'</a>&nbsp;&nbsp;&nbsp; <a href=\'javascript:view("o'.$a.'","'.$val["p.$a"].' '.$ke[0].'",2)\'><img id="o'.$a.'" src="images/occhio_off.bmp" onmouseover=\'javascript:view("o'.$a.'","'.$val["p.$a"].'@'.$ke[0].'",1)\' onmouseout=\'javascript:view("o'.$a.'","'.$val["p.$a"].'@'.$ke[0].'",0)\' title="'.$lng[38].'"></a><div id="sk'.$a.'"></div></td><td id="v'.$a.'" class="td4">'.$href.'<span id="k'.$a.'" title="'.$title.'">'.$val[$a].'</span></a></td></tr>'; 
                    } else { $title = $ke[0].' : '.Q\DB::ver($val["p.$a"].'@'.$ke[0]).' ---> '.$lng[6].' : '.date('d M Y - H:i:s',$val["t.$a"]); if(strpos($val[$a],"'") !== false) $href = '<a href=javascript:valori("v'.$a.'","'.$val[$a].'")>'; else $href = '<a href=\'javascript:valori("v'.$a.'","'.$val[$a].'")\'>';
                        echo '<tr><td class="td4">'.$a.'</td><td class="td4"><a href=\'javascript:modelli("s'.$a.'","'.$val["p.$a"].'@'.$ke[0].'")\'><span id="s'.$a.'" title="'.$title.'"></span>'.$val["p.$a"].'</a>&nbsp;&nbsp;&nbsp; <a href=\'javascript:view("o'.$a.'","'.$val["p.$a"].' '.$ke[0].'",2)\'><img id="o'.$a.'" src="images/occhio_off.bmp" onmouseover=\'javascript:view("o'.$a.'","'.$val["p.$a"].'@'.$ke[0].'",1)\' onmouseout=\'javascript:view("o'.$a.'","'.$val["p.$a"].'@'.$ke[0].'",0)\' title="'.$lng[38].'"></a><div id="sk'.$a.'"></div></td><td id="v'.$a.'" class="td4">'.$href.'<span id="k'.$a.'">'.$val[$a].'</span></a></td></tr>';
                    }
                }
            }
        } else { $ok = true; $key = $ke[0];
            if($ord == '.3' or $ord == '.6' or $ord == '.7' or $ord == '.8' or $ord == '.9') { $ok = false; if($ord == '.6') $ord = "!$ke[1]+"; elseif($ord == '.7') $ord = "!$ke[1]-"; elseif($ord == '.8') $ord = "!$ke[1]+!"; elseif($ord == '.9') $ord = "!$ke[1]-!"; else $ord = "!$ke[1]"; if($ke[2] == '0-0-0:0-0-0') { $val = Q\DB::out("$ke[0]($inizio:$fine) $ord"); $t = 0; } else { $val = Q\DB::out("$ke[0][$ke[2]]($inizio:$fine) $ord"); $t = 1; }
                echo $array.'<td class="td2 cl2">'.$ke[1].' <a href=javascript:ordina("piu",3,'.$inizio.','.$fine.','.$t.')>'.$ordpiu.'<a href=javascript:ordina("meno",3,'.$inizio.','.$fine.','.$t.')>'.$ordmeno.'</td><td class="td2 cl3">'.$lng[36].' <a href=javascript:ordina("piuq",3,'.$inizio.','.$fine.','.$t.')><img id="piuq" src="images/piuq_off.bmp" '.$piu.'<a href=javascript:ordina("menoq",3,'.$inizio.','.$fine.','.$t.')><img id="menoq" src="images/menoq_off.bmp" '.$meno.'</td></tr><tr><td height="10" colspan="3"></td></tr>';
                for($a=0; $a<$val['N']; $a++) echo '<tr><td class="td4">'.($inizio+$a).'</td><td class="td4 cl2">'.$val[$ke[1]][$a].'</td><td class="td4 cl3">'.$val['N.'.$ke[1]][$a].'</td></tr>';
            } elseif($ord == '.4') $ord = "$ke[1]+"; elseif($ord == '.5') $ord = "$ke[1]-"; elseif($ord == '.p') { $key .= '+'; $ord = $ke[1]; } elseif($ord == '.m') { $key .= '-'; $ord = $ke[1]; } else $ord = $ke[1];
            if($ok) { if($ke[2] == '0-0-0:0-0-0') { $val = Q\DB::out($key."($inizio:$fine) $ord", -1); $t = 0; } else { $val = Q\DB::out($key."[$ke[2]]($inizio:$fine) $ord", -1); $t = 1; }
                echo $array.'<td class="td2 cl2">'.$ke[0].' <a href=javascript:ordina("piu",4,'.$inizio.','.$fine.','.$t.')>'.$ordpiu.'<a href=javascript:ordina("meno",4,'.$inizio.','.$fine.','.$t.')>'.$ordmeno.'</td><td class="td2 cl3">'.$ke[1].' <a href=javascript:ordina("pac",2,'.$inizio.','.$fine.','.$t.')><img id="pac" src="images/pac_off.bmp" onmouseover=javascript:ordina("pac",1) onmouseout=javascript:ordina("pac",0) title="'.$lng[37].' ---> '.$ke[1].' : '.$lng[36].'"></a><a href=javascript:ordina("piu",2,'.$inizio.','.$fine.','.$t.')><img id="piuq" src="images/piu_off.bmp" '.$piu.'<a href=javascript:ordina("meno",2,'.$inizio.','.$fine.','.$t.')><img id="menoq" src="images/meno_off.bmp" '.$meno.'</td><td class="td2">&nbsp;Data&nbsp;</td></tr><tr><td height="10" colspan="4"></td></tr>';
                for($a=0; $a<$val['N']; $a++) { if($val["t.$ke[1]"][$a]) { $tempo = date('d M',$val["t.$ke[1]"][$a]); $tot = date('d M y - H:i:s',$val["t.$ke[1]"][$a]); } else { $tempo = ''; $tot = ''; } if(strpos($val[$a],"'") !== false) $href = '<a href=javascript:dettagli("v'.$a.'","'.$val[$a].'")>'; else $href = '<a href=\'javascript:dettagli("v'.$a.'","'.$val[$a].'")\'>'; echo '<tr><td class="td4">'.($inizio+$a).'</td><td id="v'.$a.'" class="td4">'.$href.'<span id="k'.$a.'">'.$val[$a].'</span></a><span id="m'.$a.'"></span></td><td class="td4 cl3">'.$val[$ke[1]][$a].'</td><td class="td4"><font size="2" title=" '.$lng[4].' : '.$tot.' ">'.$tempo.'</font></td></tr>'; }
            }
        }
    } else { if($ord == '.4') $ord = "$ke[0]+"; elseif($ord == '.5') $ord = "$ke[0]-"; else $ord = $ke[0];
        if($ke[2] == '0-0-0:0-0-0') { $t = 0; if($single) { $val = Q\DB::ver($ord,$single,-1); if($val) { $tempo = date('d M',$val); $tot = date('d M y - H:i:s',$val); } else { $single = ''; $tempo = ''; $tot = ''; $t = ''; } if(strpos($single,"'") !== false) $href = '<a href=javascript:dettagli("v0","'.$single.'")>'; else $href = '<a href=\'javascript:dettagli("v0","'.$single.'")\'>'; echo $array.'<td class="td2 cl3">'.$lng[3].'</td><td class="td2"><font face="Arial" size="3">&nbsp;Data&nbsp;</font></td></tr><tr><td height="10" colspan="3"></td></tr>'; echo '<tr><td class="td4">'.$t.'</td><td id="v0" class="td4">'.$href.'<span id="k0">'.$single.'</span></a><span id="m0"></span></td><td class="td4"><font size="2" title=" '.$lng[4].' : '.$tot.' ">'.$tempo.'</font></td></tr>'; echo '</table><table width="800" cellspacing="0" cellpadding="0" height="42" style="background-color:#F8F8F8; border-bottom:1px solid #F0F0F0"><tr><td align="center" colspan="2" height="12" style="background-color:#FFF; border-bottom: 1px solid #F0F0F0"></td></tr><tr><td align="center" height="30"></td><td align="center" height="30"></td></tr></table></div>'; exit; } else $val = Q\DB::out($ord."($inizio:$fine)", -1); } else { $val = Q\DB::out($ord."[$ke[2]]($inizio:$fine)", -1); $t = 1; } 
        if(!$single) {
            echo $array.'<td class="td2 cl3">'.$lng[3].' <a href=javascript:ordina("piu",2,'.$inizio.','.$fine.','.$t.')>'.$ordpiu.'<a href=javascript:ordina("meno",2,'.$inizio.','.$fine.','.$t.')>'.$ordmeno.'</td><td class="td2"><font face="Arial" size="3">&nbsp;Data&nbsp;</font></td></tr><tr><td height="10" colspan="3"></td></tr>';
            for($a=0; $a<$val['N']; $a++) { if($val["t.$a"]) { $tempo = date('d M',$val["t.$a"]); $tot = date('d M y - H:i:s',$val["t.$a"]); } else { $tempo = ''; $tot = ''; } if(strpos($val[$a],"'") !== false) $href = '<a href=javascript:dettagli("v'.$a.'","'.$val[$a].'")>'; else $href = '<a href=\'javascript:dettagli("v'.$a.'","'.$val[$a].'")\'>'; echo '<tr><td class="td4">'.($inizio+$a).'</td><td id="v'.$a.'" class="td4">'.$href.'<span id="k'.$a.'">'.$val[$a].'</span></a><span id="m'.$a.'"></span></td><td class="td4"><font size="2" title=" '.$lng[4].' : '.$tot.' ">'.$tempo.'</font></td></tr>'; }
        }
    } if(!$single) echo '</table><table width="800" cellspacing="0" cellpadding="0" height="72" style="background-color:#F8F8F8; border-bottom:1px solid #F0F0F0"><tr><td align="center" colspan="2" height="12" style="background-color:#FFF; border-bottom: 1px solid #F0F0F0"><font face="Arial" size="1">&nbsp;</font></td></tr><tr><td align="center" height="60"><select size="1" id="da_giorno">'.$giorno.'<select size="1" id="da_mese">'.$mese.'<select size="1" id="da_anno">'.$anno.' @ <select size="1" id="a_giorno">'.$giorno.'<select size="1" id="a_mese">'.$mese.'<select size="1" id="a_anno">'.$anno.'<font face="Arial" size="2">&nbsp;&nbsp;<a href="javascript:data()" title="'.$lng[39].'"><span id="xd">Data</span></a>&nbsp&nbsp|&nbsp&nbsp<a href="javascript:pos(0,0)" title="'.$lng[40].'"><span id="xp">'.$lng[41].'</span></a></font></td><td align="center" height="60"><h6>';
    if($dat) { if($inizio > 0) echo '<a href="javascript:part('.($inizio-$Qposmax).','.($inizio-1).')">'.$lng[42].'</a> '; if(($fine+1) <= $val['T']) { if($val['N'] == 0) echo '<b>( 0 )</b> <a href="javascript:part('.($fine+1).','.($fine+$Qposmax).')">'.$lng[43].'</a>'; else echo '<b>('.$inizio.' - '.$fine.')</b> <a href="javascript:part('.($fine+1).','.($fine+$Qposmax).')">'.$lng[43].'</a>'; } else echo '<b>('.$inizio.' - '.($inizio+$val['N']-1).')</b>'; } else { if(!$single) { if($inizio > 0) echo '<a href="javascript:pos('.($inizio-$Qposmax).','.($inizio-1).')">'.$lng[42].'</a> '; if(($fine+1) <= $val['T']) { if($val['N'] == 0) echo '<b>( 0 )</b> <a href="javascript:pos('.($fine+1).','.($fine+$Qposmax).')">'.$lng[43].'</a>'; else echo '<b>('.$inizio.' - '.$fine.')</b> <a href="javascript:pos('.($fine+1).','.($fine+$Qposmax).')">'.$lng[43].'</a>'; } else echo '<b>('.$inizio.' - '.($inizio+$val['N']-1).')</b>'; }} echo '</h6></td></tr></table></div>';
?>
<script>setdata(<?="'$y[0]','$y[1]','$y[2]','$z[0]','$z[1]','$z[2]',$dat"?>);</script>
</body>
</html>