<?php

namespace Quantico;

class Qout extends SYS
{
    protected static function parentesi($key,$keyass,$valass,$opz,$type,$sel) { if(strpos($keyass, ',') > 1) { $val = array(' ','#','@'); $par = array(')',']','}'); foreach($par as $p) { $j = strpos($keyass, $p); if($j > 1) { $j++; if(!in_array($keyass[$j],$val)) { $j = explode($p, $keyass, 2); return Qout::Qdbout($j[0]."$p ".$j[1].$sel.$key,$valass,$opz); }}}} if(strpos($key, ',') > 1) { if($sel == '#') return Qout::Qdbout("$keyass #$key",$valass,$opz,$type); else return Qout::Qdbout("$keyass @$key",$valass,$opz); } return false; }
    protected static function time12($keyval,$type=0,$ora=0,$arr=false) { if(!$keyval) return false; $key = SYS::val(Qout::adesso($keyval)); if(is_array($arr)) $keyval = $arr; if($type === _T1_) { for($a=0, $u=count($keyval); $a<$u; $a++) $key["t.$a"] = (int)substr($keyval[$a],0,10); } elseif($type === _T2_) { if(!$ora) $ora = SYS::time(); for($a=0, $u=count($keyval); $a<$u; $a++) $key["t.$a"] = $ora - (int)substr($keyval[$a],0,10); } return $key; }
    protected static function adesso_aggiorna($keyval,$k,$kv) { if(is_array($keyval) && $k) { $pos = array_keys($keyval,$k); foreach($pos as $p) $keyval[$p] = $kv; return $keyval; } else return false; }
    protected static function adesso($keyval){ global $Qdatabase; global $Qpostime; $per = $Qdatabase.$Qpostime; $keyper = []; if(is_array($keyval)) $key = SYS::u($keyval); else $key = array($keyval); foreach($key as $k) { if($k[10] != ':') { $z = substr($k,0,3).'/'.substr($k,3,$k[12]); $per = "$Qdatabase$Qpostime/$z"; $pern = "$per/keyn.php"; $perv = "$per/keyv.php";
        if(isset($keyper[$z.'v'])) { $ok = true; while($ok){ $j = array_search($k,$keyper[$z.'v']); if($j > 1) { $kv = $keyper[$z.'n'][$j]; $z = substr($kv,0,3).'/'.substr($kv,3,$kv[12]); if(!isset($keyper[$z.'v'])) { $keyval = Qout::adesso_aggiorna($keyval,$k,$kv); $per = "$Qdatabase$Qpostime/$z"; $pern = "$per/keyn.php"; $perv = "$per/keyv.php"; if(file_exists($pern)){ $keyper[$z.'n'] = file($pern); $keyper[$z.'v'] = file($perv); } else $ok = false; } else $keyval = Qout::adesso_aggiorna($keyval,$k,$kv); $k = $kv; } else $ok = false; }} else { if(file_exists($pern)){ $keyper[$z.'n'] = file($pern); $keyper[$z.'v'] = file($perv); $ok = true; while($ok){ $j = array_search($k,$keyper[$z.'v']); if($j > 1) { $kv = $keyper[$z.'n'][$j]; $z = substr($kv,0,3).'/'.substr($kv,3,$kv[12]); if(!isset($keyper[$z.'v'])) { if(is_array($keyval)) $keyval = Qout::adesso_aggiorna($keyval,$k,$kv); $per = "$Qdatabase$Qpostime/$z"; $pern = "$per/keyn.php"; $perv = "$per/keyv.php"; if(file_exists($pern)){ $keyper[$z.'n'] = file($pern); $keyper[$z.'v'] = file($perv); } else $ok = false; } else $keyval = Qout::adesso_aggiorna($keyval,$k,$kv); $k = $kv; } else $ok = false; }}}}} if(is_array($keyval)) return $keyval; else return $k; }
    protected static function selezione($keyval,$num,$opz=0) { if(!$keyval) return false; $key = []; if($opz) { if($num[3]) { $inizio = $num[3]; $fine = $num[4]; if(!$num[5]) $keyval = array_reverse($keyval); foreach($keyval as $a) { $n = substr($a,0,10); if($n >= $inizio && $n <= $fine) $key[] = $a; } if(count($key) == 0) return false; $keyval = $key; $key = []; }} if(!isset($num[7])) return false; if(strstr($num[7],'-')) { if(!$num = SYS::sel($num,count($keyval))) return false; } if($num[0] == '') { global $Qposdef; $fine = $Qposdef-1; } else $fine = $num[0]-3; if($num[2] == -1) $inizio = 0; else { $fine++; if($num[6]) { $inizio = $fine; $fine = $num[2]; } else $inizio = $num[2]; } $n = count($keyval)-1; if($inizio > $n) return false; if($fine > $n) $fine = $n; if($num[6]) { for($a=$fine; $a>=$inizio; $a--) $key[] = $keyval[$a]; } else { for($a=$inizio; $a<=$fine; $a++) $key[] = $keyval[$a]; } return $key; }
    protected static function ora($o, $t, $ora) { $v = array(0,0,0,23,59,59); $val = false; if(!strpos($o[0], '-')) { if(count($t) == 1) $t = explode('-', date('d-m-Y', $ora)); if(isset($o[0])) { $v[0] = $o[0]; $v[3] = $v[0]; } if(isset($o[1])) { $v[1] = $o[1]; $v[4] = $v[1]; } if(isset($o[2])) { $v[2] = $o[2]; $v[5] = $v[2]; }} if(isset($t[0]) && isset($t[1]) && isset($t[2])) { if(strlen($t[0]) > 0 && strlen($t[1]) > 0 && strlen($t[2]) == 4) { $val[0] = mktime($v[0], $v[1], $v[2], $t[1], $t[0], $t[2]); $val[1] = mktime($v[3], $v[4], $v[5], $t[1], $t[0], $t[2]); $val[2] = $t[0].$t[1].$t[2]; } elseif(strlen($t[0]) == 4 && strlen($t[1]) > 0 && strlen($t[2]) > 0) { $val[0] = mktime($v[0], $v[1], $v[2], $t[1], $t[2], $t[0]); $val[1] = mktime($v[3], $v[4], $v[5], $t[1], $t[2], $t[0]); $val[2] = $t[2].$t[1].$t[0]; } return $val; } return false; }
    protected static function solokey($key) { if(strpos($key, '{') > 1) $key = substr($key, 0, strpos($key, '{')); if(strpos($key, '[') > 1) $key = substr($key, 0, strpos($key, '[')); if(strpos($key, '(') > 1) $key = substr($key, 0, strpos($key, '(')); return $key; }
    protected static function operatori($val, $x=null){ if($x === null) { if($val[1][0] == '!') { $val[1] = substr($val[1],1); $val[20] = $val[1]; } if($val[1][strlen($val[1])-1] == '!') { $val[1] = substr($val[1], 0, -1); $val[18] = true; } $val = Qout::operatori_segno($val); } else { if($val[1][$x][0] == '!') { $val[1][$x] = substr($val[1][$x],1); $val[20] = $val[1][$x]; } if($val[1][$x][strlen($val[1][$x])-1] == '!') { $val[1][$x] = substr($val[1][$x], 0, -1); $val[18] = true; } $val = Qout::operatori_segno($val,$x); } if(!$val[16]) $val[18] = false; return $val; }
    protected static function operatori_segno($val, $x=null){ if($x === null) { $y = $val[1][strlen($val[1])-1]; if($y == '+') { $val[1] = substr($val[1], 0, -1); $val[16] = $val[1]; $val[17] = 1; } elseif($y == '-') { $val[1] = substr($val[1], 0, -1); $val[16] = $val[1]; $val[17] = 2; }} else { $y = $val[1][$x][strlen($val[1][$x])-1]; if($y == '+') { $val[1][$x] = substr($val[1][$x], 0, -1); $val[16] = $val[1][$x]; $val[17] = 1; } elseif($y == '-') { $val[1][$x] = substr($val[1][$x], 0, -1); $val[16] = $val[1][$x]; $val[17] = 2; }} return $val; }
    protected static function analisi($key) { global $Qposmax; $Qmax = $Qposmax + 2; $ora = SYS::time(); if(strpos($key, ',') > 1) $key = SYS::u(explode(',',$key),true); $a = strpos($key, '{'); $val = array(false,false,-1); for($e=3; $e<19; $e++) $val[$e] = false; $ok = false; $z = 0;
        if($a > 1) { $b = strpos($key, '}'); $z = $b; if($b > $a) { $val[9] = trim(substr($key, $a+1, $b-$a-1)); if(strpos($key, ',') > 1) { $v = SYS::u(explode(',',$key)); $tmp = $val[9]; $val[13] = []; foreach($v as $c) { if($c[0] == '_' || $c[1] == '_') SYS::$dataval = true; if(strpos($c,$tmp) === false) { if(!strstr($c,'!#') && !strstr($c,'!@')) $val[13][] = $c; } else { if($c[0] != '!') $val[1] = substr($c, 0, strpos($c, '{')); else { if($c[1] != '#' && $c[1] != '@') { $val[1] = substr($c,1,strpos($c, '{')-1); $ok = true; } else return Qerror(2, 30, $c); } $tmp = false; }}} else { if($key[0] == '_' || $key[1] == '_') SYS::$dataval = true; if($key[0] != '!') $val[1] = substr($key, 0, $a); else { if($key[1] != '#' && $key[1] != '@') { $val[1] = substr($key, 1, $a-1); $ok = true; } else return Qerror(2, 30, $key); }} $c = explode(':', $val[9]);
            if(count($c) == 1) { if($val[9][0] == '>') { $val[15] = 1; $v = substr($val[9],1); if(SYS::$dataval) $v = SYS::dataval($v); if(is_numeric($v)) $val[10] = $v; } elseif($val[9][0] == '<') { $val[15] = 2; $v = substr($val[9],1); if(SYS::$dataval) $v = SYS::dataval($v); if(is_numeric($v)) { $val[10] = $v; $val[12] = 1; }} else { if(SYS::$dataval) $val[9] = SYS::dataval($val[9]); if(is_numeric($val[9])) { $val[10] = $val[9]; $val[11] = $val[9]; }}} elseif(count($c) == 2) { if(SYS::$dataval) { $c[0] = SYS::dataval($c[0]); $c[1] = SYS::dataval($c[1]); } if(is_numeric($c[0])) $val[10] = $c[0]; if(is_numeric($c[1])) $val[11] = $c[1]; if($val[11] < $val[10]) { $b = $val[11]; $val[11] = $val[10]; $val[10] = $b; $val[12] = 1; }} else return false; SYS::$dataval = false; $val = Qout::operatori($val); }
        } $a = strpos($key, '['); // $val[3] = Tempo PARTENZA    $val[4] = Tempo ARRIVO     $val[5] = STATO ---> true = MAX:min | false = min:MAX
        if($a > 1) { if(!$z || ($a-$z) == 1) { $b = strpos($key, ']'); if($b > $a) { if(!$val[10]) $val[1] = substr($key, 0, $a); $val[8] = trim(substr($key, $a+1, $b-$a-1)); $d = explode(':', $val[8]); if(count($d) == 1) { if(strpos($val[8],'=')) { $c = substr($key,$a+1,$b-$a-1); $key = str_replace($c,"$c:$c",$key); return Qout::analisi($key); } else { if(strpos($val[8],'-')) { $t = explode('-', $val[8]); $o = explode('.', $val[8]); $v = Qout::ora($o, $t, $ora); $val[3] = $v[0]; $val[4] = $v[1]; $val[5] = true; } else { $o = explode('.', $val[8]); $val[5] = true; $val[4] = $ora; if(isset($o[2])) $val[3] = $ora - $o[0]*3600 + $o[1]*60 + $o[2]; elseif(isset($o[1])) $val[3] = $ora - $o[0]*60 + $o[1]; elseif(isset($o[0])) $val[3] = $ora - $o[0]; }}}
            elseif(count($d) == 2) { $e1 = explode('=', $d[0]); $e2 = explode('=', $d[1]); if(count($e1) == 1 && count($e2) == 1) { $t = explode('-', $d[0]); $o = explode('.', $d[0]); $v1 = Qout::ora($o, $t, $ora); $val[3] = $v1[0]; $t1 = $v1[2]; $t = explode('-', $d[1]); $o = explode('.', $d[1]); $v2 = Qout::ora($o, $t, $ora); $val[4] = $v2[1]; $t2 = $v1[2]; if($val[4] < $val[3]) { $val[5] = true; $val[3] = $v2[0]; $val[4] = $v1[1]; }} elseif(count($e1) == 2 && count($e2) == 2) { if(strpos($e1[0], '-')) { $t = explode('-', $e1[0]); $o = explode('.', $e1[1]); $v1 = Qout::ora($o, $t, $ora); $val[3] = $v1[0]; } if(strpos($e1[1], '-')) { $t = explode('-', $e1[1]); $o = explode('.', $e1[0]); $v1 = Qout::ora($o, $t, $ora); $val[3] = $v1[0]; } if(strpos($e2[0], '-')) { $t = explode('-', $e2[0]); $o = explode('.', $e2[1]); $v2 = Qout::ora($o, $t, $ora); $val[4] = $v2[1]; } if(strpos($e2[1], '-')) { $t = explode('-', $e2[1]); $o = explode('.', $e2[0]); $v2 = Qout::ora($o, $t, $ora); $val[4] = $v2[1]; } if($val[4] < $val[3]) { $val[5] = true; $val[3] = $v2[0]; $val[4] = $v1[1]; }}} else return false; if(!$val[3] || !$val[4]) { $val[3] = false; $val[4] = false; } $key = $val[1].substr($key,$b+1); $z = 0; }}
        } $a = strpos($key, '('); // $val[2] = Posizione PARTENZA    $val[0] = Posizione ARRIVO     $val[6] = STATO ---> true = MAX:min | false = min:MAX
        if($a > 1) { if(!$z || ($a-$z) == 1) { $b = strpos($key, ')'); if($b > $a) { if(!$val[10]) $val[1] = substr($key, 0, $a); $val[7] = trim(substr($key, $a+1, $b-$a-1)); $d = explode(':', $val[7]); if(count($d) == 1) { $val[0] = abs($val[7]) + 2; if($val[0] == 2 || $val[0] > $Qmax) $val[0] = $Qmax; } elseif(count($d) == 2) { $val[2] = abs($d[0]); $val[0] = abs($d[1]) + 2; if($d[0] > $d[1]) $val[6] = true; if(($val[0] - $val[2]) > $Qmax) $val[0] = $val[2] + $Qmax; } else return false; }}} if($ok) $val[14] = $val[1]; if(!$val[1]) $val[1] = $key; if(!$val[10]) { if(strpos($key, ',') > 1) { $v = SYS::u(explode(',',$key)); $val[1] = []; $x = -1; foreach($v as $a) if($a) { $x++; if($a[0] != '!') { $val[1][$x] = $a; $val = Qout::operatori_segno($val,$x); } else { if($a[1] != '#' && $a[1] != '@') { $val[1][$x] = substr($a,1); $val = Qout::operatori($val,$x); $val[14] = $val[1][$x]; break; } else return Qerror(2, 30, $a); }}} else { if($key[0] != '!') { if(!$val[1]) $val[1] = $key; $val = Qout::operatori_segno($val); } else { if($val[1] != '#' && $val[1] != '@') { $val[1] = substr($val[1],1); $val = Qout::operatori($val); $val[14] = $val[1]; } else return Qerror(2, 30, $val); }}} if($val[14]) $val[14] = Qout::solokey($val[14]); return $val; 
    }
    protected static function Qdbout($keys=null, $valass=null, $opz=null, $type=0, $all=null){ global $Qdatabase; $ora = SYS::time();
        if(is_array($opz) || is_array($valass)) { if(is_array($opz)) { if($keys[0] == '*') { $keys = strtolower(substr($keys,1)); if(file_exists("class/Qai/$keys.php")) { require_once "Qai/$keys.php"; return Qai::query($valass, $opz); } return false; } $tmp = $valass; $valass = $opz; $opz = $tmp; } require_once 'Qsx.php'; return Qsx::search($keys, $valass, $opz, $type, $all, $ora); } else $valass = SYS::speciali($valass,1); $keyval['K'][] = 0; global $Qposdef;
        if(strpos($keys, ' ') > 1) { $ky = explode(' ', $keys, 2); if(!isset($ky[1][1])) return false; if($ky[1][0] == ',') { if(strpos($ky[0], '#')) { $k = explode('#',$ky[0]); return Qout::Qdbout($k[0].' #'.$k[1].$ky[1]); } elseif(strpos($ky[0], '@')) { $k = explode('@',$ky[0]); return Qout::Qdbout($k[0].' @'.$k[1].$ky[1]); }} if(strpos($ky[1], ',') !== false) { if($ky[0][0] == '!') return Qout::Qdbout($ky[0]); } $pk = substr($ky[0],-1); if($pk == '!') { $ky[0] = substr($ky[0],0,-1); $key = '!'.$ky[1]; } else $key = $ky[1]; if($ky[0][0] != '!') $keyass = $ky[0]; else $keyass = substr($ky[0],1);
            if($valass == null && $opz == null && $type == 0) { $numkeyass = Qout::analisi($keyass); if($numkeyass[0] == '' && $numkeyass[3] == '') $keyass .= "($Qposdef)"; else { if($keyass[0] == '#' || $keyass[0] == '@') return Qout::Qdbout("$keyass $key", 0, 0); else { if(strpos($numkeyass[1], '#') > 1) { $ky = explode('#', $numkeyass[1], 2); if($numkeyass[17] == 1) $ky[0] .= '+'; elseif($numkeyass[17] == 2) $ky[0] .= '-'; if($numkeyass[3]) $ky[0] .= '['.$numkeyass[8].']'; if($numkeyass[0]) $ky[0] .= '('.$numkeyass[7].')'; return Qout::Qdbout($ky[0].'#'.$ky[1].' '.$key); }}}}
            if($keyass[0] == '#' || $keyass[0] == '@') { $ky = explode(' ', $keys, 2); if($ky[0][0] == '@' && $valass > 0) return Qout::Qdbout($ky[0],$valass,$opz,$type,explode(',',$ky[1]));
                if($valass !== null) { $numkey = Qout::analisi($ky[1]); if(is_array($numkey[1])) return false; $key = SYS::combina($numkey[1],1); $numkeyass = Qout::analisi($ky[0]); $keyass = $numkeyass[1];
                    if($key) { $keyper = SYS::combina($keyass, 2); if($keyass) { if($keyass[0] == '#') $keypers = "$keyper/keyp.php"; else $keypers = "$keyper/keyc.php"; if(file_exists($keypers)){ $fp = file($keypers); $key = rtrim($key); if($keyass[0] == '#') $p = '.0'; else $p = '.1'; $keyper .= '/'.$key.$p; if($valass === _T1_ || $valass === _T2_) $o = 2; else $o = 1; $a = array_search($key."\n",$fp); 
                        if($a > 1) { $fp = []; if($keyass[0] == '#') { $fx = SYS::leggi($keyper ,0 ,$numkeyass ,$o); for($x=2, $u=count($fx); $x<$u; $x++) { $n = $x-2; if($valass) { $f = explode('.', rtrim($fx[$x])); $fp[$n] = $f[0]."\n"; $qt = SYS::tempo($valass,$f[1],$ora); if($qt !== false) $keyval["t.$n"] = $qt; } else $fp[$n] = $fx[$x]; }} else { $fx = SYS::leggi($keyper ,0 ,$numkeyass ,1 ,$o); for($x=2, $u=count($fx); $x<$u; $x++) { $f = explode('.', $fx[$x]); $i = count($f)-1; $n = $x-2; if($f[0][0] == '-') { $fp[$n] = substr($f[0], 12); $tempo = (int)substr($f[0], 2, 10); $keyval['-.'.$n] = base64_encode($fp[$n]); } else { $fp[$n] = $f[0]; $keyval['-.'.$n] = 0; $tempo = (int)substr($f[$i], 0, 10); } $keyval["p.$n"] = $f[1]; for($h=2; $h<$i; $h++) $keyval["p.$n"] .= '.'.$f[$h]; if($valass === _T1_) $keyval["t.$n"] = $tempo; elseif($valass === _T2_) $keyval["t.$n"] = $ora - $tempo; }} if($fp) { $vl = SYS::val($fp); foreach($vl as $val) $keyval[] = $val; unset($keyval['K']); require_once 'Qmix.php'; return Qmix::flusso($numkey,$keyval,(int)$fx[0],(int)$fx[1],1,$numkeyass); }}}}
                    }
                } return false;
            } 
            if(strpos($keyass, '#') > 1) { require_once 'Qmix.php'; return Qmix::outmix(QKEYBASE, $key, $keyass, $valass, $opz, $ora, 1); }
            if(strpos($keyass, '@') > 0) { require_once 'Qcl.php'; return Qcl::key($key, $keyass, $valass, $opz, $ora); } 
            if($keys[0] == '$') { require_once 'Qdk.php'; return Qdk::key($key, $keyass, $valass, $opz, $type, $ora); }
            if($keys[0] == '-') { require_once 'Qdk.php'; return Qdk::space($key, $keyass, $valass, $opz, $type); }
        } else { $key = $keys; $keyass = 0;
            if($key[0] == '#' || $key[0] == '@') { if($valass != null && $key[0] == '@') return Qout::Qdbout($valass.$key,$opz,null,0,$all); $key = substr($key, 1); $keyper = SYS::combina($key, 2); if(!$keyper) return false; if($keys[0] == '#') $keyper .= '/keyp.php'; else $keyper .= '/keyc.php'; $cfp = 0; if(file_exists($keyper)){ $file = file($keyper); for($a=2, $ua=count($file); $a<$ua; $a++) { $k = explode('.', rtrim($file[$a])); if($k[count($k)-1] != '@') { $keyval[$a-2] = rtrim(QKEYBASE[$k[0]]); for($b=1, $ub=count($k); $b<$ub; $b++) $keyval[$a-2] .= '.'.rtrim(QKEYBASE[$k[$b]]); $cfp++; }} if($cfp) { $keyval['N'] = $cfp; $keyval['T'] = $cfp; unset($keyval['K']); return $keyval; }} return false; }
            if($key[0] == '$') { require_once 'Qdk.php'; return Qdk::keymix($key, $keyval, $valass, $opz, $ora); }
            if($key[0] == '-') { require_once 'Qdk.php'; return Qdk::mix($key, $valass, $opz, $type, $ora); } $ccc = strpos($keys, '@'); $ccl = strpos($keys, '#');
            if($ccc > 0) { require_once 'Qcl.php'; return Qcl::mix($keys, $valass, $opz, $type, $all, $ora, $ccl); }
            if($ccl > 1) { $ky = explode('#', $keys, 2); $key = $ky[1]; $keyass = $ky[0]; if($j = Qout::parentesi($key,$keyass,$valass,$opz,$type,'#')) return $j; $numkeyass = Qout::analisi($keyass);
            //---------------------------------------------------------------------------------------------->>>>>>> INIZIO Query  --->  Qout::Qdbout('user.email(20)#foto',2)
            if($numkeyass[0] != '' || $numkeyass[3] != '') {
                if($valass == null || $valass === _T1_ || $valass === _T2_) return Qout::Qdbout("$keyass #$key", $valass, $opz, $type);
            } else { $numkey = Qout::analisi($key); 
                if($valass == null && $opz == null) { if($numkey[0] != '' || $numkey[3] != '') { if($numkey[3]) $keyass .= '['.$numkey[8].']'; if($numkey[0]) $keyass .= '('.$numkey[7].')'; } return Qout::Qdbout("$keyass #$key"); } if($opz !== _T1_ && $opz !== _T2_) { if($valass === _T1_ || $valass === _T2_) { if($numkey[0] != '' || $numkey[3] != '') { if($numkey[3]) $keyass .= '['.$numkey[8].']'; if($numkey[0]) $keyass .= '('.$numkey[7].')'; return Qout::Qdbout($keyass.' #'.$numkey[1],$valass); }}} $pk = substr($keyass,-1);
                if($pk == '!') { $keyass = substr($keyass,0,-1); $key = '!'.$key; } $key = $numkey[1]; $per = SYS::combina($key); $per[] = 0; $id = SYS::keyvalass($keyass, $valass, $per, 0, $type); if($opz) $m = 2; else $m = 1; $fx = SYS::leggi($Qdatabase.'/'.$id ,0 ,$numkey, $m); $kat = []; $tat = []; $nick = false; for($b=2; $b<$fx[1]+2; $b++) { $c = $b-2; if($opz) { $m = explode('.', rtrim($fx[$b])); if($m[0][0] == '#') { $kat[$c] = substr($m[0],1)."\n"; $tat[$c] = $m[1]; $nick = true; } else { $keyval[$c] = $m[0]; $nick = false; $qt = SYS::tempo($opz,$m[1],$ora); if($qt !== false) $keyval["t.$c"] = $qt; }} else { if($fx[$b][0] == '#') { $kat[$c] = substr($fx[$b],1); $tat[$c] = false; $nick = true; } else { $keyval[$c] = rtrim($fx[$b]); $nick = false; }}} if($nick) $keyval = Qout::time12($kat,$opz,$ora,$tat); if($fx[1]) { if(isset($keyval['K'])) { $numkey[18] = $keyval['K']; unset($keyval['K']); } require_once 'Qmix.php'; return Qmix::flusso($numkey,$keyval,(int)$fx[0],(int)$fx[1],1); }
            } return false; } //---------------------------------------------------------------------------->>>>>>>>> FINE Query
        } $numkeyass = Qout::analisi($keyass); $numkey = Qout::analisi($key,1); $keytmp = false; $per = false; $lnk = false; $cln = false;
        if(is_array($numkey[1])) { if($numkeyass[0] == false && $numkeyass[3] == false && $valass != null) return Qout::Qdbout($keyass, $valass, $opz, explode(',',$key), $type); else { if(!$numkey[14]) { if($valass == null) { $numkeyass[0] = $Qposdef + 2; $valass = 0; }} else { if($numkeyass[0] == false && $numkeyass[3] == false) $numkeyass[0] = $Qposdef + 2; else $valass = null; } $per = SYS::combina($numkeyass[1]); }} else { if($numkeyass[0] != '' || $numkeyass[3] != '') { if($key[0] == '!') { if($valass == null) $valass = 0; $opz = null; } $per = SYS::combina($numkey[1]); } else { if($valass == null && $opz == null && $type == 0) { if($numkeyass[1] == '0') $valass = 0; elseif($numkeyass[0] == false && $numkeyass[2] == -1) { $numkeyass[0] = $Qposdef + 2; $valass = 0; } else $keyass .= "($Qposdef)"; } if($numkey[1][0] == '#' || $numkey[1][0] == '@') return Qout::Qdbout($keyass.$key,$valass,$opz,$type); $key = $numkey[1]; $per = SYS::combina($key); }}
        if($per) { $keyper = $Qdatabase; $keyval = false; 
            if($keyass) { require_once 'Qmix.php'; return Qmix::outmix(QKEYBASE, $key, $keyass, $valass, $opz, $ora, 0, $all); } else { if($valass !== null) { if(!$type) { if($numkey[0] != false || $numkey[3] != false) return Qout::Qdbout($keys, null, $valass, 1); }} if(!is_array($per)) return false; foreach($per as $a) $keyper .= '/'.$a; $numkeyok = false; if($valass == null) { global $Qpostime; $fp = SYS::leggi($keyper,0,$numkey); $keyper = $Qpostime; if($fp) { if(!$fp[0]) return false; else $numtot = (int)$fp[0]; } else return false; } else { if($all) $hashpos = $all; else $hashpos = SYS::hashpos(Qhash($valass), $per); if($opz === _T3_) { $keyperindex = "$hashpos/index.php"; if(file_exists($keyperindex)) { $fp = file($keyperindex); return (int)substr($fp[count($fp)-1],0,10); } else return false; } $keyperindex = "$hashpos/link.php"; $numtot = SYS::tot($keyper); if(file_exists($keyperindex)) { $fp = file($keyperindex); $fk = file("$hashpos/keys.php"); } else return false; }
            if(is_array($type)) { $type = array_values(array_unique($type)); $y = 0; $fpt = [0,0]; $fkt = [0,0]; $numkeyok = []; foreach($type as $tp) { $numkeyok[$y] = Qout::analisi($tp); if($numkeyok[$y][1][0] == '#') { $fine = ".0\n"; $tp = substr($numkeyok[$y][1], 1); } elseif($numkeyok[$y][1][0] == '@') { $fine = ".1\n"; $tp = substr($numkeyok[$y][1], 1); } elseif($numkeyok[$y][1][0] == '_') { $fine = "\n"; $tp = substr($numkeyok[$y][1], 1); } else $fine = "\n"; $fe = explode('.',$tp); $keymsg = ''; $x = 0; foreach($fe as $f) { $j = array_search($f."\n",QKEYBASE); if($j > 1) { $keymsg .= $j.'.'; $x++; }} if(count($fe) == $x) { $keymsg = substr($keymsg,0,-1); $keymsg .= $fine; $j = array_search($keymsg,$fk); if($j > 1) { $fkt[] = $fk[$j]; $fpt[] = $fp[$j]; $y++; }}} $fp = $fpt; $fk = $fkt; } $cfp = count($fp); $keytmp = false; $nick = false;
            for($a=2; $a<$cfp; $a++) { $nick = false; if(strlen($fp[$a]) < 64) { $keytmp[$a-2] = $fp[$a]; // *********************** Hyper Velocità
                } else { $keytmp[$a-2] = false; $ff = explode('/', $fp[$a]); if($ff[0]) { // *************************************** è stato clonato
                    if($opz === _T1_ || $opz === _T2_) $o=2; else $o=1; if(!$numkeyok) $u = $numkey; else $u = $numkeyok[$a-2]; $dati = SYS::leggi($Qdatabase.'/'.rtrim($fp[$a]),0,$u,$o); $keymsg = SYS::kb($fk[$a], '@', 1); $dat = []; for($b=2; $b<$dati[1]+2; $b++) { $c = $b-2; $dat[$c] = rtrim($dati[$b]); if($opz) { $f = explode('.',$dat[$c]); $dat[$c] = $f[0]; for($d=1, $u=count($f)-1; $d<$u; $d++) $dat[$c] .= '.'.$f[$d]; $qt = SYS::tempo($opz,$f[count($f)-1],$ora); if($qt !== false) $dat["t.$c"] = $qt; }}
                } else { // ******************************************************************************************************** è stato linkato
                    if($opz) $m = 2; else $m = 1; if(!$numkeyok) $u = $numkey; else $u = $numkeyok[$a-2]; $dati = SYS::leggi($Qdatabase.'/'.rtrim($fp[$a]),0,$u,$m); $dat = []; $kat = []; $tat = []; $keymsg = SYS::kb($fk[$a], '#', 1); for($b=2; $b<$dati[1]+2; $b++) { $c = $b-2; if($opz) { $m = explode('.', rtrim($dati[$b])); if($m[0][0] == '#') { $kat[$c] = substr($m[0],1)."\n"; $tat[$c] = $m[1]; $nick = true; } else { $dat[$c] = $m[0]; $nick = false; if($opz === _T1_) $dat['t.'.$c] = $m[1]; elseif($opz === _T2_) $dat['t.'.$c] = $ora - $m[1]; }} else { if($dati[$b][0] == '#') { $kat[$c] = substr($dati[$b],1); $tat[$c] = false; $nick = true; } else { $dat[$c] = rtrim($dati[$b]); $nick = false; }}}} if($nick) $dat = Qout::time12($kat,$opz,$ora,$tat); if($dati[1]) { $keyval['K'][$a-2] = $keymsg; $keyval[$keymsg] = $dat; $keyval['N.'.$keymsg] = (int)$dati[1]; $keyval['T.'.$keymsg] = (int)$dati[0]; }}
            } if($keytmp) { $a = 1; $vl = SYS::val($keytmp); foreach($vl as $val) { $a++; if($val !== false) { if($valass == null) { $v = $a-2; $keyval[$v] = $val; $qt = SYS::tempo($opz,$fp[$a],$ora); if($qt !== false) $keyval["t.$v"] = $qt; } else { $keymsg = SYS::kb($fk[$a], '', 0, 'Qout'); if($fp[$a][strlen($fp[$a])-2] == '_') $keymsg = '_'.$keymsg; $keyval['K'][$a-2] = $keymsg; $keyval[$keymsg] = $val; $qt = SYS::tempo($opz,$fp[$a],$ora); if($qt !== false) $keyval["t.$keymsg"] = $qt; }}} if(isset($keyval['K'])) $keyval['K'] = SYS::sort($keyval['K']); } $cfp -= 2; if($cfp) { $keyval['N'] = $cfp; $keyval['T'] = $numtot; return $keyval; }}
        } return false;
    }
}